name: Build

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type-check
        run: npm run type-check
      # - name: Test
      #   run: npm test

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Install dependencies
        run: uv sync --dev
      - name: Lint
        run: uv run poe lint
      - name: Type-check
        run: uv run poe type-check
      # - name: Test
      #   run: uv run poe test
