name: Build

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run CI tasks
        run: npm run ci-tasks

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Install dependencies
        run: uv sync --dev --all-extras
      - name: Run CI tasks
        run: uv run poe ci-tasks
