name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Install Python dependencies
        run: uv sync --dev
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install NodeJS dependencies
        run: npm ci
        working-directory: frontend
      - name: Run prerelease checks
        run: poe prerelease

  publish-npm:
    runs-on: ubuntu-latest
    environment: release
    defaults:
      run:
        working-directory: ./frontend
    needs: [prerelease]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    needs: [prerelease]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Install dependencies
        run: uv sync --dev
      - name: Build
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4

  create-release:
    needs: [publish-npm, publish-pypi]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
